### NUMPY ESSENTIALS

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


Create a NumPy array with values [10, 20, 30, 40]

In [2]:
import numpy as np
arr1=np.array([10,20,30,40])
print(arr1)

[10 20 30 40]


Print the type of the array

In [3]:
type(arr1)

numpy.ndarray

Create a 2D Array

In [6]:
arr2= np.array([[1,2,3],[4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


Find - shape
dimension
size
datatype

In [8]:
print(arr2.shape)
print(arr2.ndim)
print(arr2.size)
print(arr2.dtype)

(2, 3)
2
6
int64


Create Zero Matrix

In [12]:
arr3 = np.zeros((2,3))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
print(arr3.dtype)

float64


In [14]:
arr3 = arr3.astype(int)

In [15]:
print(arr3.dtype)

int64


Create a 2x4 array of ones

In [16]:
arr4 = np.ones((2,4))
print(arr4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Create a 2x2 array filled with value 7

In [17]:
arr5 = np.full((2,2),7)
print(arr5)

[[7 7]
 [7 7]]


Generate 5 random numbers between 0 and 1

In [19]:
print(np.random.rand(5))

[0.27552746 0.60511049 0.49936271 0.63782775 0.44871434]


Using arange Create numbers from 1 to 10

In [21]:
print(np.arange(1,11))

[ 1  2  3  4  5  6  7  8  9 10]


Create even numbers between 10 and 20

In [22]:
print(np.arange(10,21,2))

[10 12 14 16 18 20]


Create 5 evenly spaced values between 0 and 1

In [23]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


Indexing

In [25]:
arr = np.array([10,20,30,40])
print(arr[0])

10


In [26]:
print(arr[1])

20


In [27]:
print(arr[-1])

40


In [28]:
arr1= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr1[0:2,0:2])

[[1 2]
 [4 5]]


In [29]:
print(arr1[0:2,1:])

[[2 3]
 [5 6]]


In [30]:
print(arr1[1:,0:2])

[[4 5]
 [7 8]]


In [31]:
print(arr1[1:,1:])

[[5 6]
 [8 9]]


In [36]:
print(arr1[0:,0])

[1 4 7]


In [37]:
print(arr1[0,0:])

[1 2 3]


In [39]:
np.diag(arr1,k=0)

array([1, 5, 9])

Convert 1D to 2D Array

In [41]:
arr1 = np.array([1,2,3,4,5,6])
print(arr1)
arr1= arr1.reshape(3,2)
print(arr1)

[1 2 3 4 5 6]
[[1 2]
 [3 4]
 [5 6]]


Looping through array

In [43]:
arr1= np.array([[1,2,3],[4,5,6],[7,8,9]])
for i in arr1:
    for j in i:
        print(j)

1
2
3
4
5
6
7
8
9


Add 10 to Each Element

In [46]:
print(arr1+10)  #broadcasting

[[11 12 13]
 [14 15 16]
 [17 18 19]]


Multiply Arrays

In [47]:
arr4 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr4*arr5)

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [48]:
arr4 = np.array([[1,2,3],[4,5,6], [7,8,9]])
arr5 = np.array([[1,2,3],[4,5,6], [7,8,9]])
print(arr4@arr5)

[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


Find mean, median, mode

In [51]:
arr = np.array([10,20,30,40])

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.median(arr))

25.0
40
10
25.0


In [52]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


In [53]:
arr1 = np.array([10,10,10,10,20,30])
from scipy import stats
print(stats.mode(arr1))

ModeResult(mode=np.int64(10), count=np.int64(4))


You have marks of students:

marks = [45, 78, 90, 66, 88, 72, 59]
Tasks:  
Convert to NumPy array  
Find average marks  
Find highest & lowest marks  
Find students scoring above average  
Add 5 grace marks to all students

In [57]:
marks = [45, 78, 90, 66, 88, 72, 59]
marks = np.array([45, 78, 90, 66, 88, 72, 59])
print(np.mean(marks))
print("Highest marks is ", np.max(marks),"Lowest marks is ",  np.min(marks))
print(marks+5)
print(marks[marks>np.mean(marks)])

71.14285714285714
Highest marks is  90 Lowest marks is  45
[50 83 95 71 93 77 64]
[78 90 88 72]


Temperature recorded for 7 days:

temps = [30, 32, 35, 31, 29, 40, 38]
Tasks:  
Find days with temperature > 35  
Count number of hot days   

In [58]:
temp = np.array([30, 32, 35, 31, 29, 40, 38])
hot_days = temp[temp>35]
print(len(hot_days))

2


Employee salaries:  

salary = [25000, 40000, 35000, 50000, 45000]
Tasks:  
Increase all salaries by 10%  
Find employees earning > 40000   

In [64]:
salary = np.array([25000, 40000, 35000, 50000, 45000])
inc_by_10= salary+0.1*salary
emp = inc_by_10[inc_by_10>40000]
print(inc_by_10)
print(emp)

[27500. 44000. 38500. 55000. 49500.]
[44000. 55000. 49500.]


A grayscale image (3x3 pixels):

img = [[100, 150, 200],
       [50, 75, 125],
       [0, 25, 255]]
Tasks:  
Convert to NumPy array  
Increase brightness by 20  
Clip values to max 255  

In [67]:
img = np.array([[100, 150, 200], [50, 75, 125], [0, 25, 255]])
brightness = img+10
clipped = np.clip(brightness, 0, 255)
print(brightness)
print(clipped)

[[110 160 210]
 [ 60  85 135]
 [ 10  35 265]]
[[110 160 210]
 [ 60  85 135]
 [ 10  35 255]]


Sales for 5 days:

sales = [200, 300, 250, 400, 350]
Tasks:  
Find total sales  
Find day with highest sales  
Find days where sales < 300  

In [73]:
sales = np.array([200, 300, 250, 400, 350])
Total_sales = sum(sales)
print(Total_sales)
print(max(sales))
sales1= sales[sales<300]
print(sales1)

1500
400
[200 250]


Scores:

scores = [55, 65, 75, 85, 95]
Tasks:  
Get students with grades ≥ 75  
Replace scores < 60 with 60  

In [75]:
scores = np.array([55, 65, 75, 85, 95])
grades = scores[scores>=75]
print(grades)
adjusted = np.where(scores < 60, 60, scores)
print(adjusted)

[75 85 95]
[60 65 75 85 95]
